name: 🚀 Publish Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build assets (Vite or Mix)
      - name: Build assets
        run: |
          npm install
          npm run build

      # Setup PHP + Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Deploy Laravel app (everything except /public)
      - name: Deploy Laravel App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./                # repo root
          server-dir: /home/sahittya/laravel_project/
          exclude: |
            public/*
            node_modules/*
            .git*
            .github/*
            storage/logs/*
            storage/framework/sessions/*

      # Deploy public folder only
      - name: Deploy Public Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./public/
          server-dir: /home/sahittya/public_html/

